Change devs.yaml for newer links and a bio in Fery (so me)
Pridecraft-Studios/website pull request #5
Opened 2024-12-20 21:26 UTC by NormalFery

Pretty much a single commit I am VERY scared about because i've never seen anything that isn't .html , or .css files 
i am shaking right now

This PR literally does nothing more but add a bio for me and change the website to point to the new domain

2024-12-20 21:28 UTC, blryface commented
sob

2024-12-20 21:29 UTC, blryface requested changes
otherwise lgtm. If it already does, just change it to https

2024-12-20 21:29 UTC, blryface commented on src/lib/vars/devs.yaml
> +    website: http://normalfery.es
Maybe make your website support ssl first?

2024-12-21 03:06 UTC, Ampflower commented
Merging once fixing the link to use HTTPS.

2024-12-21 03:17 UTC, merged